---
title: "Curriculum Vitae"
editor: visual
---

PDF Version [here](docs/Curriculum_Vitae.pdf)

## Contact Information

{{< fa envelope >}} [l.clair@uwinnipeg.ca](mailto:l.clair@uwinnipeg.ca)

{{< fa phone >}} (204) 789-4216

{{< fa paper-plane >}} Department of Economics   
&nbsp;&nbsp;&nbsp;&nbsp; University of Winnipeg   
&nbsp;&nbsp;&nbsp;&nbsp; 515 Portage Avenue   
&nbsp;&nbsp;&nbsp;&nbsp; Winnipeg, MB, Canada   
&nbsp;&nbsp;&nbsp;&nbsp; R3B 2E9



## Academic Profiles and Website

- {{< fa user >}} Personal Website: [www.lclair.ca](http://www.lclair.ca)
- {{< fa seedling >}} Canadian Centre for Agri-Food Research in Health and Medicine: [www.sbrc.ca/clair](http://www.sbrc.ca/clair)
- {{< fa graduation-cap >}}  Rate My Professor: [www.ratemyprofessors.com](http://www.ratemyprofessors.com/ShowRatings.jsp?tid=2334849)


## Education

- Ph.D. Economics (2017), McMaster University (Supervisor Dr. Jeffrey Racine)   
- M.A. Economics (2012), Memorial University of Newfoundland 
- B.Sc. Pure Mathematics and Economics (2008), Memorial University of Newfoundland 


## Current Positions

- Associate Professor (2022-), Department of Economics, University of Winnipeg.
- Principal Investigator (2017-), Agriculture/Health Economics, Canadian Centre for Agri-Food Research in Health and Medicine.
- Assistant Professor, Part-Time Nil Salary (2019-), Department of Community Health Sciences, University of Manitoba. 


## Previous Positions

- Assistant Professor (2017-2022), Department of Economics, University of Winnipeg.
- Postdoctoral Fellow (2016-2017), Memorial University of Newfoundland (Supervisor Dr. Lynn Gambin)


## Fields of Specialization

- Health Economics
- Econometrics and Statistics


## Professional Affiliations

- Canadian Economics Association
- Canadian Health Economic Association
- Canadian Econometric Study Group
- American Economics Association

## Courses Taught
### University of Winnipeg

- *Graduate*:

  - GECON 7000, MAE Research Project   
  - GECON 7003, Cost-Benefit Analysis

- *Undergraduate*:

  - ECON 1102, Intro - Microeconomics   
  - ECON 1103, Intro - Macroeconomics   
  - ECON 1201, Quantitative Methods for Business and Economics   
  - ECON 3201, Introduction to Econometrics   
  - ECON 3310, Economics of Canadian Health Care   

### Memorial University of Newfoundland

- *Undergraduate*:

  - Economics 2020, Introductory Macroeconomics


## Student Supervision and Training

- *Thesis Supervisor*    
   - Dhingra, Vaishali (2022, M.A. in Applied Economics, University of Winnipeg)
		
	
- *Thesis Committee Member*:
   - Khawar, Hibah (2018, M.Sc Food and Human Nutritional Sciences, University of Manitoba)
	
- *Research Assistants*:

	- Kashton, Jared (2021-present, M.A. Economics, York University)
	- Ahmed, Jamil (2020-2021, M.A. in Applied Economics, University of Winnipeg)
	- Epp, Tiffani (2020, B.A., University of Manitoba)
	- Goulet-Kilgor, Callum (2020, B.B.A. University of Winnipeg)
	- Eze, Nkiruka (2019-2020, M.A. Economics, University of Lancaster)
	- Awowole, Olusegun (2018, M.A.E.P. Economics, University of Winnipeg)
  - Ezeani, Chukwudi (2018, M.A.E.P. Economics, University of Winnipeg)

- *Teaching Assistants*:

	- Charlotte Belbas, Lab instructor for Econ 3201 Introduction to Econometrics, September 7 - December 6, 2021.
	- Sadia Zohaib (MAE, University of Winnipeg), TA for Econ 1201 Quantitative Methods for Economics and Business, September 8 - December 4, 2020.
	- Joy Dakil (MAEP, University of Winnipeg), TA for Econ 1201 Quantitative Methods for Economics and Business, January 6 - April 4, 2020.

	


- *Mentorship*:

  - 2020-2021 CRDCN Policy challenge mentor for Adelia Jacobs, MSc Human Nutrition, University of British Columbia
	

## Teaching Assistantships

- *Graduate*:

  - Econometrics I, McMaster University.   
  - Microeconomics Theory for Public Policy, McMaster University.

- *Undergraduate*:

  - Public Sector Economics, McMaster University.   
  - Introductory Macroeconomics, McMaster University.   
  - Intermediate Microeconomics, McMaster University.   
  - Economics Clinic, McMaster University.   
  - Introductory Macroeconomics, McMaster University. 
  - Introduction to Game Theory, McMaster University.
  - Introductory Macroeconomics, McMaster University.
  - International Monetary Economics, McMaster University.

- *Other*:

  - English Teacher (2008-2009), Lycée Gambetta (Tourcoing, France).



## University Service

- *Committees*:

  - Senate Student Appeals Committee (Member, 2021-)
	- University Study Leave Committee (Member, 2020-)
	- Department Curriculum Committee (Member, 2017-)
	- Department Research and Ethics Committee (Member, 2017-)
	- Department Personnel Sub-Committee for Candidate Search (Member, 2017-2018) 
	
- *Events*:

	- Open House 2021, February 10, 2021
	- First Year Orientation, September 2, 2020
	- Open House 2019, February 20, 2019

- *Media*:

  - Interview for The University of Winnipeg NewsCentre, April 9, 2018. ([Link](http://news-centre.uwinnipeg.ca/allposts/does-heart-disease-lead-to-dementia/)) 

- *External Service*:

	- Volunteer at the Cardiac Classic Golf Tournament (August 13th, 2018) 	


## Grants and Fellowships

1. Social Sciences and Humanities Research Council of Canada - Insight Grant, *co-applicant with Melanie O'Gorman (Principal Investigator), Kerry Black, and Stewart Hill*.  
    **Title:** How Important are Water and Sanitation? Investigating the Associations between Water/Sanitation and Well-being in First Nations in Manitoba.   
    **Amount:**  \$211,624.     
    **Date:**  April 1, 2022 - March 31, 2025.

1. Canadian Agriculture Partnership - Processing and Value Added Grant, *with Miyoung Suh (Principal Investigator), Champa Wijekoon, Glen Ross, James House, and Joan Niquanicappo*.   
**Title:** Smart Vertical Farm for Health in Northern Communities.      
**Amount:**  \$454,445.     
**Date:**  April 1, 2020 - March 31, 2023.
 
1. Canadian Agriculture Partnership - Research and Innovation Grant, *principal investigator with Dr. Carl Taylor and Nkiru Eze*.     
**Title:** Socioeconomic Impact of Legume-Based Health Care Intervention for Treating Peripheral Artery Disease.     
**Amount:**  \$35,000.     
**Date:**  April 1, 2020 - August 31, 2021

1. University of Winnipeg Major Research Grant, *principal investigator with Dr. Carl Taylor and Nkiru Eze*.      
**Title:** Estimating the Cost of Peripheral Artery Disease in Manitoba.    
**Amount:** $7,500.     
**Date:**  April 1, 2019 - March 31, 2020

1. Canada Agriculture Partnership - Research and Innovation, *co-investigator with Dr. Delfin Rodrigez-Leyva (Principal Investigator), and Dr. Grant Pierce*. **Title:** The effect of flax milk on arterial hypertension: Evaluation of blood pressure response by 24 hour ambulatory blood pressure monitoring.     
**Amount:**  $103,825.      
**Date:**  April 1, 2019 - March 31, 2021

1. Canada Agriculture Partnership - Research and Innovation, *co-investigator with Dr. Davinder Jassal (Principal Investigator), Dr. Grant Pierce, and Dr. Pawan Singal*.     
**Title:** Flaxseed prevents broken hearts in breast cancer patients (CANFLAX study).     
**Amount:**  $229,113.     
**Date:**  April 1, 2019 - March 31, 2022

1. Canada Agriculture Partnership - Research and Innovation, *co-investigator with Dr. Harold Aukema (Principal Investigator), Dr. Grant Pierce, Dr. Carla Taylor, Dr. Peter Zahradka, and Dr. Samantha Pauls*.      
**Title:** Cost-Effectiveness Analysis of the Anti-Inflammatory Effects of Flax Oil.     
**Amount:**  $103,258.     
**Date:**  April 1, 2019 - March 31, 2021.

1. Canada Agriculture Partnership - Grain Innovation Hub, *co-investigator with Dr. Ben Albensi (Principal Investigator), Dr. Mandana Modirrousta, Dr. Colleen Millikin, and Dr. Grant Pierce*.      
**Title:** Effects of dietary Flaxseed on Memory and Cognition.     
**Amount:**  $215,373.     
**Date:**  April 1, 2019 - March 31, 2021

1. Manitoba Medical Service Foundation Operating Grant, *principal investigator with collaborators Dr. Hope Anderson (CCARM) and Dr. Chris Anderson (University of Manitoba)*.     
**Title:** Estimating the Relationship Between Cardiovascular Health and the Use of Neurodegenerative Pharmaceuticals.    
**Amount:** $30,000.      
**Date:** April 1, 2017 - March 31, 2019

1. Newfoundland and Labrador SUPPORT Patient-Oriented Research Grant, *co-investigator with Dr. Sheila Garland (Principal Investigator), Ken Fowler, Karine Calfour, Geoff Eaton, Breanna Lane*.      
**Title:** Young Adults with Cancer in their Prime (YACC PRIME): A Patient Oriented Collaborative Study.     
**Amount:** $75,000.      
**Date:** June 1 2017 - May 31, 2018.

1. Postdoctoral Fellowship, Collaborative Applied Research in Economics, Memorial University of Newfoundland.      
**Title:** A Review of the Newfoundland and Labrador Health Care System: An Economist's Perspective.      
**Amount:** $55,000.      
**Date:** September 1, 2016 - August 31, 2017.

1. PhD. Graduate Scholarship, McMaster University.      
**Amount:** $7200 per annum.      
**Date:** Academic Years 2012 - 2016.

1. Travel Award, Canadian Society of Epidemiology and Biostatistics Conference.       
**Title:** Prevalence Estimates of Five Mental Health Conditions: A Comparison of Approaches       
**Amount:** $500.      
**Date:** June 1, 2015.


1. M.A. Graduate Scholarship, Memorial University of Newfoundland.       
**Amount:** $5000.      
**Date:** September 1, 2011 - August 31, 2012.

## Awards 

- Canadian Journal of Public Health Editors Choice Award for ``Examining differences in diet quality between Canadian Indigenous and non-Indigenous adults: results from the 2004 and 2015 Canadian Community Health Survey Nutrition Surveys" with Natalie Riediger, Jeffrey Laplante, and Adriana Mudryj.(2022)
- Certificate of Merit for Exceptional Performance as a Member of the Faculty of Business and Economics in the 2019-2020 Academic Year, University of Winnipeg. (2021)
 

## Peer Reviewed Publications


1. Clair, Luc, Hope Anderson, Christopher Anderson, Okechukwu Ekuma, and Heather Prior. (2022). ``Cardiovascular Disease and the Risk of Dementia: A Survival Analysis Using Administrative Data from Canada". *Canadian Journal of Public Health*. DOI: [https://doi.org/10.17269/s41997-021-00589-2](https://link.springer.com/article/10.17269/s41997-021-00589-2).

1.  Riediger, Natalie, Jeffrey Laplante, Adriana Mudryj, and Luc Clair. (2022). ``Examining differences in diet quality between Canadian Indigenous and non-Indigenous adults: results from the 2004 and 2015 Canadian Community Health Survey Nutrition Surveys".  *The Canadian Journal of Public Health*. DOI: [10.17269/s41997-021-00580-x](https://link.springer.com/article/10.17269\%2Fs41997-021-00580-x).

1. Riediger, Natalie, Laplante, Jeffrey, Mudryj, Adriana, and Clair, Luc. (2021). ``Diet quality among Indigenous and non-Indigenous children and youth in Canada in 2004 and 2015: a repeated cross-sectional design".  *Public Health Nutrition*. Jun 10:1-10. DOI: [10.1017/S1368980021002561](https://www.cambridge.org/core/journals/public-health-nutrition/article/diet-quality-among-indigenous-and-nonindigenous-children-and-youth-in-canada-in-2004-and-2015-a-repeated-crosssectional-design/723ECCB88D8E26FB50B13E0FAFE3C036)

1. Mahon KN, SN Garland, G Eaton, K Chalifour, BE Lane, K Fowler, L Gambin, and L Clair. (2021). ``The Financial Impact of Cancer on Canadian Young Adults". *Journal of Cancer Survivorship: Research and Practice*.

1. Pauls, Samantha, Youjia Du, Luc Clair, Tanja Winter, Harold M. Aukema, Carla G. Taylor, Peter Zahradka. (2020). ``Impact of Age, Menopause, and Obesity on Oxylipins Linked to Vascular Health". *Arteriosclerosis, Thrombosis, and Vascular Biology*, 41(2): 883-897. 

1. Gibson, Grant and Luc Clair. (2019). ``Oh Brother How Art Thou? Differential Reporting of Unmet Need - Evidence from Ontario". *Social Science and Medicine*. 243. 112632. 

1. Clair, L. (2019), ``Nonparametric Kernel Regression Using Complex Survey Data", The Econometrics of Complex Survey Data. *Advances in Econometrics*, Vol. 39, Emerald Publishing Limited, Bingley, pp. 173-208.

1. Moghadasian, Mohammed H., Luc Clair, Francesca Bonomini, Gaia Favero, and Rita Rezzani. (2018). ``Obesity and Related Disorders: An International Perspective". *Current Research in Diabetes \& Obesity Journal.* 7(5): 55721. 


## Work Submitted for Publication

- Abo Aoun, Mohamed; Meek, Benjamin; Clair, Luc; Wikstrom, Sara; Prasad, Benjamin; Modirrousta, Mandana. "Prognostic factors in major depressive disorder: comparing responders and non-responders to Repetitive Transcranial Magnetic Stimulation (rTMS), a naturalistic retrospective chart review". *Revise and Resubmit at  The Canadian Journal of Psychiatry*.

## Working Papers

- Clair, Luc. (2017). ``Private Supplemental Insurance and  Mental Health Care Utilization in Canada: An Investigation using Nonparametric Estimation Methods." *Collaborative Applied Research in Economics, Department of Economics, Memorial University of Newfoundland*.


## Technical Reports

- Clair, Luc, Angela Tan, Carla Taylor, and Peter Zahradka. ``Estimating the Additional Health Care Costs Associated with Peripheral Artery Disease in Manitoba.'' Prepared for Manitoba Agriculture on October 31, 2021.

- Clair, Luc. ``Estimating the Economic Impact of Agri-Food-Based Health Care Interventions". Prepared for Manitoba Agriculture on March 31, 2021. 


## Works in Progress

- Probability-Weighted Nonparametric Conditional PDF Estimation
- Nonparametric Instrumental Variable Estimation Using Complex Survey Data 
- Socioeconomic Impact of Pulse-Based Treatment for Peripheral Artery Disease 
- Nonparametric Multiple Imputation
- Writing an R package for nonparametric kernel estimation methods for survey data 
- Genome 360 Phase II: Manitoba's Provincial Applied Genomics Enterprise Platform
- The effect of flax milk on arterial hypertension: Evaluation of blood pressure response by 24 hour ambulatory blood pressure monitoring with Dr. Delfin Rodrigez-Leyva, and Dr. Grant Pierce
- Flaxseed prevents broken hearts in breast cancer patients (CANFLAX study) with Dr. Davinder Jassal, Dr. Grant Pierce, and Dr. Pawan Singal 
- Cost-Effectiveness Analysis of the Anti-Inflammatory Effects of Flax Oil with Dr. Grant Pierce, Dr. Carla Taylor, Dr. Peter Zahradka, and Dr. Samantha Pauls 
- Effects of dietary Flaxseed on Memory and Cognition with Dr. Ben Albensi, Dr. Mandana Modirrousta, Dr. Colleen Millikin, and Dr. Grant Pierce 



## Referee Activities
### Academic Journals

- The Canadian Journal of Public Health
- The Journal of the Prevention of Alzheimer's Disease
- Alzheimer's and Dementia
- Reviewed chapters in ``Macroeconomics: Canada in the Global Economy, 11the Edition" for Pearson Publishing.
- Quality of Life Research
- Advances in Econometrics


### Textbooks

- Reviewed chapters in ``Macroeconomics: Canada in the Global Economy, 11the Edition" for Pearson Publishing.


## Grant Selection Committees

- Genome Canada


## Conference Presentations and Invited Lectures

- CIHR Smart Cities Lecture Series, March 30, 2022. ``Introduction to Health Economics". 
- Millennium Library Skywalk Lecture Series, Winnipeg, Manitoba February 16, 2022, ``Estimating the Relationship Between Cardiovascular Disease and Dementia".
- Dementia Journal Club, University of Manitoba, February 25, 2021. ``Estimating the Relationship Between CVD and dementia". 
- Department of Community Health Sciences Bold Ideas Colloquium Series, University of Manitoba, February 7, 2020, ``Nonparametric Econometric Methods and their Applications to Health Data".
- Millennium Library Skywalk Lecture Series, Winnipeg, Manitoba February 5, 2020, ``Estimating the Relationship Between Cardiovascular Disease and Dementia".
- Canadian Research Data Centre Network 2019 National Conference, Halifax, Nova Scotia, October 24th, 2019, ``Estimating the Relationship Between Cardiovascular Disease and Dementia".
- St. Boniface Hospital Foundation, May 30, 2019, ``Agriculture and Health Economics at the St. Boniface Hospital Research Centre".
- Manitoba Agriculture, April 26, 2019, ``Agriculture and Health Economics at the St. Boniface Hospital Research Centre".
- Department of Economics Seminar, University of Manitoba, September 28, 2018, ``Nonparametric Instrumental Variable Estimation Using Complex Survey Data".
- 52nd Annual Conference of the Canadian Economics Association, McGill University, June 3, 2018, ``Private Supplemental Insurance and  Mental Health Care Utilization in Canada: An Investigation using Nonparametric Estimation Methods".
- Food for Thought Seminar, Canadian Centre for Agri-Food Research in Health and Medicine, December 12, 2017, ``Health Economics: Theory, Methods, and Applications".
- Department of Seminar, College of Pharmacy, University of Manitoba, November 29, 2017, ``Private Supplemental Insurance and  Mental Health Care Utilization in Canada: An Investigation using Nonparametric Estimation Methods".  
- Bank of Canada Conference on the * Econometrics of Survey Data: Theory and Applications}, Bank of Canada, October 18, 2017. ``Nonparametric Kernel Regression Using Complex Survey Data".
- Department of Economics Seminar, Memorial University of Newfoundland, September 8, 2017, ``Private Supplemental Insurance and  Mental Health Care Utilization in Canada: An Investigation using Nonparametric Estimation Methods".  
- 51st Annual Conference of the Canadian Economics Association, St. Francis Xavier University, June 2, 2016, ``Probability-Weighted Nonparametric Conditional PDF Estimation".
- 50th Anniversary of the Department of Economics at Memorial University of Newfoundland (Invited), March 1, 2017, ``Supplemental Health Insurance and the Use of Mental Health Services in Canada".
- Department of Economics Seminar, University of Winnipeg, February 3, 2017, ``Probability-Weighted Nonparametric Conditional PDF Estimation".
- 50th Annual Conference of the Canadian Economics Association, University of Ottawa, June 4, 2016. ``Nonparametric Kernel Regression using Complex Survey Data".
- NY Camp Econometrics (Poster), April 8-10, 2016, ``Nonparametric Kernel Regression for Mixed Data Types Using Complex Survey Data".
- Department of Economics Seminar, McMaster University, January 5, 2016, ``Nonparametric Kernel Regression for Mixed Data Types Using Complex Survey Data". 
- Atlantic Summer Institute on Healthy and Safe Communities Symposium on Child and Youth Mental Health (Invited), August 19, 2015, ``Sharing Information and Using Large Data Sets Across Sectors for Collective Impact".
- Canadian Society of Epidemiology and Biostatistics Conference, June 1, 2015, ``Prevalence Estimates of Five Mental Health Conditions: A Comparison of Approaches".
 


## Languages

- English (Native)
- French: read, write, speak



