---
title: "Teaching Philosophy"
editor: visual
date: today
date-format: long
---

I have been fortunate in my life to have studied under great professors who conveyed both simple and complex materials in a lucid and compelling manner. I base my own brand of teaching on a mixture of my most favoured pedagogical characteristics from past instructors. While these instructors differed in many ways, they all demonstrated a high level of preparation, which I believe to be a key to their success as an effective educator. When it comes to teaching, being prepared not only translates to a full understanding of the material but also how best to teach the material in a logical order and the correct medium for presenting the material (e.g. seminar, lecture, PowerPoint, blackboard, video, and/or discussion). Economic theory encompasses a myriad of topics, which may require different approaches to effectively deliver the appropriate message to students.  Being prepared promotes an open learning environment as it allows students to ask a broad range of questions, leading to engaging discussions. Questioning the material provides feedback and a method for auditing one's understanding. A prepared teacher is more flexible and presents topics in ways that facilitate student engagement. 

Other aspects of teaching I incorporate are student engagement, assessments that stimulate independent thinking, and review of pre-requisite concepts. Teaching also provides external benefits for understanding economic theory, which can be translated to students through collaboration. 

## Student Engagement

Student engagement cultivates learning as the students' attention will be focused on the coursework and, by increasing interest in a topic, will encourage independent study. Engagement is nurtured by forming a connection between economic theory and the student. At the University of Winnipeg, I teach video-on-demand courses for introductory microeconomic and macroeconomic theory. For these courses, I teach one section in a classroom equipped with audiovisual equipment and the lectures are filmed and posted later to the University's distance education portal for two online sections. This has posed a challenge to engage students who are viewing the lectures on their own, at different times, and without direct interaction with their instructor. I have found success; however, by presenting as many real-world examples as possible. By incorporating real-world examples into lesson plans, students can relate to economic theory and develop an intuitive understanding of the principle ideas. Health economics offers a variety of case studies to draw from when presenting economic theory, especially in introductory courses. Health care markets suffer from every source of market failure, providing an example for most topics in introductory microeconomic theory. Furthermore, health economic topics can be used to reinforce concepts in macroeconomics. For example, health insurance can be used to help explain risk pooling when discussing the benefits of financial institutions and investment diversification. 

Also, by connecting students with practitioners in the community, from government officials to business leaders to civil society leaders, students get a better sense of the application of economic concepts in the real world. This is easier to achieve in small classes as the types of assignments and discussions can better accommodate student participation and examples can be tailored to that particular audience.  As I build my network in Winnipeg, I am always searching for potential guest speakers for my classes. 

## Assessments for Independent Thinking

Carefully designed assessments encourage independent thinking and provide experience for the real word. As educators, we wish not to develop economists who can simply restate theory but can apply these concepts to research that benefits all of society. I organize my assessments such that students show (1) they understand the basics; (2) they understand more complex material; and (3) they can apply what they have learned to a new problem. Challenging students to synthesize the concepts they have learned in order to solve a problem fosters creativity and resourcefulness. Furthermore, assessments that mirror real-world assignments help prepare students for employment in all areas, including government, private sector, and academia. 

## Review of Pre-requisite Concepts

My approach to learning is sometimes similar to my search for a lost item: I start with the last place I had it. "It" in this case is an understanding; I go to where I last had a solid understanding of the material work my way forward. In my experience, many students lack an understanding of the underlying mathematical methods or do not possess the foundational concepts in economics to properly solve problems. I find reviewing the supporting material provides these students with the ability to better solve problems in a variety of cases. It helps to clarify the logical connection between the theoretical concepts in economics and the quantitative tools used to support them. Some students who have strong quantitative skills have trouble grasping normative concepts, while other students may possess economic intuition but struggle with mathematics. In a classroom setting, reviewing the pre-requisite concepts allows students to start with a more equal distribution of knowledge.

## External Benefit from Teaching

I truly enjoy teaching. I derive a great deal of fulfillment from helping others gain new knowledge and providing them with the tools to solve future problems. Teaching often results in a positive externality as helping others navigate through material has the added benefit of giving the instructor a better understanding of economic theory. Many revelations I have had in my own studies came from tutoring other students. For example, by drawing on lessons of different concepts to help others understand a particular problem, as the teacher, you begin to form connections between topics and develop a greater understanding of economic theory. These connections are then passed on to others through teaching. It is for this reason, I believe teaching is an important aspect of academia. These same benefits can be achieved through collaboration. By grouping students with varying economic knowledge, students can help fill the gaps in each other's understandings, offer new insights, and identify underlying connections between economic concepts.

 
