---
title: "Teaching"
editor: visual
---

## Courses Taught

### The University of Winnipeg

#### Graduate

-   GECON 7000, M.A. in Applied Economics Research Project

-   GECON 7003, Cost-Benefit Analysis

#### Undergraduate

-   ECON 1102, Intro: Microeconomics

-   ECON 1103, Intro: Macroeconomics

-   ECON 1201, Quantitative Methods for Business and Economics

-   ECON 3201, Introduction to Econometrics

-   ECON 3310, Economics of Canadian Health Care

-   ECON 3316, Cost-Benefit Analysis and Program Evaluation

### Memorial University of Newfoundland

-   Economics 2020, Introductory Macroeconomics

## Student Supervision and Training

-   Thesis Supervisor

    -   Dhingra, Vaishali (2022, M.A. in Applied Economics, University of Winnipeg)

-   Thesis Committee Member:

    -   Khawar, Hibah (2018, M.Sc Food and Human Nutritional Sciences, University of Manitoba)

-   Research Assistants:

    -   Kashton, Jared (2021-present, M.A. Economics, York University)

    -   Ahmed, Jamil (2020-2021, M.A. in Applied Economics, University of Winnipeg)

    -   Epp, Tiffani (2020, B.A. University of Manitoba)

    -   Goulet-Kilgor, Callum (2020, B.B.A. University of Winnipeg)

    -   Eze, Nkiruka (2019-2020, M.A. Economics, University of Lancaster)

    -   Awowole, Olusegun (2018, M.A. Economics, University of Winnipeg)

    -   Ezeani, Chukwudi (2018, M.A. Economics, University of Winnipeg)

-   Teaching Assistants

    -   Charlotte Belbas, Lab instructor for Econ 3201 Introduction to Econometrics, September 7 - December 6, 2021.

    -   Sadia Zohaib (MAE, University of Winnipeg), TA for Econ 1201 Quantitative Methods for Economics and Business, September 8 - December 4, 2020.

    -   Joy Dakil (MAEP, University of Winnipeg), TA for Econ 1201 Quantitative Methods for Economics and Business, January 6 - April 4, 2020.

-   Mentorship:

    -   2021 CRDCN Policy challenge mentor for Adelia Jacobs, MSc Human Nutrition, University of British Columbia

## Teaching Assistantships

### Graduate:

-   Econometrics I, McMaster University.
-   Microeconomics Theory for Public Policy, McMaster University.

### Undergraduate:

-   Public Sector Economics, McMaster University.
-   Introductory Macroeconomics, McMaster University.
-   Intermediated Microeconomics, McMaster University.
-   Economics Clinic, McMaster University.
-   Introductory Macroeconomics, McMaster University.
-   Introduction to Game Theory, McMaster University.
-   Introductory Macroeconomics, McMaster University.
-   International Monetary Economics, McMaster University.

### Other:

-   English Teacher (2008-2009), Lycée Gambetta (Tourcoing, France).

 

Updated on: `r Sys.Date()`
